#
# Copyright (C) 2021-2022 by TeamYukki@Github, < https://github.com/TeamYukki >.
#
# This file is part of < https://github.com/TeamYukki/YukkiMusicBot > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/TeamYukki/YukkiMusicBot/blob/master/LICENSE >
#
# All rights reserved.


import asyncio

from pyrogram import Client as c

API_ID = input("\nEnter Your API_ID:\n > ")
API_HASH = input("\nEnter Your API_HASH:\n > ")

print("\n\n Enter Phone number when asked.\n\n")

i = c(":memory:", api_id=API_ID, api_hash=API_HASH)


async def main():
    await i.start()
    ss = await i.export_session_string()
    xx = f"HERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n\n`{BQBdATOkT1CK0sHb8iZLJnD8vGUOAvAWijbeyynMxXIZU5QqtG-31p-vPbxeaRN4I8yfTWmXTy0QTXBmV9OaU-VWrkxymkcmdSHWbFGiOsMqCVNnp5QiitbnU1nIc-bCytBIEK4Goi1CkIPMrFxie2s_DwQHio4as6heSFUPDVQcQRZ8xiQjEnJ2BQiVdy5rMDRKz7qBRYp1tPuDb6vdIc4CcOqYUN1F4R-Izr14JS7bBsDmqMkiqRpwkbkWUMpM5mtTDSOi4WjDhHdNKlqfgwRMTgJtUxa6asInc7tIiDH76zauvLb6Hk_D7JEu7LjE5twMHbXDnukJb4cpWGJmUEXnah4Q4QA}`\n\nGENERATED BY YUKKI"
    ok = await i.send_message("me", xx)
    print("\nHERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n")
    print(f"\n{BQBdATOkT1CK0sHb8iZLJnD8vGUOAvAWijbeyynMxXIZU5QqtG-31p-vPbxeaRN4I8yfTWmXTy0QTXBmV9OaU-VWrkxymkcmdSHWbFGiOsMqCVNnp5QiitbnU1nIc-bCytBIEK4Goi1CkIPMrFxie2s_DwQHio4as6heSFUPDVQcQRZ8xiQjEnJ2BQiVdy5rMDRKz7qBRYp1tPuDb6vdIc4CcOqYUN1F4R-Izr14JS7bBsDmqMkiqRpwkbkWUMpM5mtTDSOi4WjDhHdNKlqfgwRMTgJtUxa6asInc7tIiDH76zauvLb6Hk_D7JEu7LjE5twMHbXDnukJb4cpWGJmUEXnah4Q4QA}\n") 
    print("\nGENERATED BY YUKKI\n")


asyncio.run(main())
